
img_size: [94, 24]
is_CBL: true
cuda: True
num_workers: 8
# path
CBLtrain: "data/CBLPRD-330k_v1/train.txt"
CBLval: "data/CBLPRD-330k_v1/val.txt"
pretrained_model: '' #'weights/CBL-acc.822.pth' ''
save_folder: './weights/'
tb_log_dir: null  # 'runs/May29_10-53-54_willing-MS-7A38' null
# train opt.
# max_epoch: 5
init_epoch: 0
add_epochs: 10
epoch_p_save: 3
epoch_p_test: 1
# learn paramaters
train_batch_size: 256
test_batch_size: 256
learning_rate: 0.001
# lr_schedule: [8, 11, 12, 14, 16] # for adam
lr_schedule: [4, 8, 12, 14, 16] # for RMS
momentum: 0.9
weight_decay: 2e-5
optim: RMS # adam
# model
model_name: LPR_CTC
lpr_max_len: 8 #license plate number max length.
lpr_class_predict: false
lpr_CTC_predict: True